In [6]:
%load_ext autoreload
%autoreload 2
%reload_ext autoreload
from q1_softmax import *
from q1_classifier import *

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [2]:
test_softmax_basic()

Running basic tests...
Basic (non-exhaustive) softmax tests pass



In [3]:
test_cross_entropy_loss_basic()

Basic (non-exhaustive) cross-entropy tests pass



In [4]:
with tf.Session() as session:
    z = tf.random_uniform((3,3))
    a = tf.Variable(4)
    init = tf.initialize_all_variables()
    #init = tf.global_variables_initializer()
    session.run(init)
    print z.eval()
    print a.eval()

[[ 0.92336953  0.08881867  0.33767712]
 [ 0.86538041  0.7084806   0.84649336]
 [ 0.50179279  0.84819055  0.90348732]]
4


In [11]:
test_SoftmaxModel()

Epoch 0: loss = 63.15 (0.031 sec)
Epoch 1: loss = 21.69 (0.010 sec)
Epoch 2: loss = 11.66 (0.010 sec)
Epoch 3: loss = 7.79 (0.010 sec)
Epoch 4: loss = 5.80 (0.011 sec)
Epoch 5: loss = 4.61 (0.010 sec)
Epoch 6: loss = 3.82 (0.010 sec)
Epoch 7: loss = 3.25 (0.010 sec)
Epoch 8: loss = 2.83 (0.010 sec)
Epoch 9: loss = 2.51 (0.010 sec)
Epoch 10: loss = 2.25 (0.010 sec)
Epoch 11: loss = 2.04 (0.010 sec)
Epoch 12: loss = 1.86 (0.010 sec)
Epoch 13: loss = 1.71 (0.010 sec)
Epoch 14: loss = 1.59 (0.010 sec)
Epoch 15: loss = 1.48 (0.010 sec)
Epoch 16: loss = 1.38 (0.010 sec)
Epoch 17: loss = 1.30 (0.011 sec)
Epoch 18: loss = 1.23 (0.010 sec)
Epoch 19: loss = 1.16 (0.011 sec)
Epoch 20: loss = 1.10 (0.011 sec)
Epoch 21: loss = 1.05 (0.012 sec)
Epoch 22: loss = 1.00 (0.012 sec)
Epoch 23: loss = 0.95 (0.010 sec)
Epoch 24: loss = 0.91 (0.010 sec)
Epoch 25: loss = 0.88 (0.010 sec)
Epoch 26: loss = 0.84 (0.010 sec)
Epoch 27: loss = 0.81 (0.010 sec)
Epoch 28: loss = 0.78 (0.010 sec)
Epoch 29: loss = 0.75