In [10]:
%load_ext autoreload
%autoreload 2
%reload_ext autoreload
from q2_initialization import *
from q2_NER import *

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [3]:
test_initialization_basic()

Running basic tests...
Basic (non-exhaustive) Xavier initialization tests pass



In [8]:
test_initialization()

Running your tests...
Expected Xavier initializer:  0.454858826147
Actual Xavier initializer:  0.45374


In [17]:
test_NER()

Epoch 0
Training loss: 1.04356265068265068
Training acc: 0.810196394282
Validation loss: 0.992531657219

[[42562    26    39    38    94]
 [  317  1481    37   165    94]
 [  449    38   726    25    30]
 [  862    97    46   968   119]
 [  727    21     1    43  2357]]
Tag: O - P 0.9476 / R 0.9954
Tag: LOC - P 0.8906 / R 0.7073
Tag: MISC - P 0.8551 / R 0.5726
Tag: ORG - P 0.7813 / R 0.4627
Tag: PER - P 0.8749 / R 0.7485
Total time: 94.8493640423
Epoch 1
Training loss: 0.985366165638165638
Training acc: 0.861777518036
Validation loss: 0.980269372463

[[42452    44    37    94   132]
 [  242  1647    12   119    74]
 [  321    37   859    22    29]
 [  690   120    28  1132   122]
 [  556    26     3    27  2537]]
Tag: O - P 0.9591 / R 0.9928
Tag: LOC - P 0.8789 / R 0.7865
Tag: MISC - P 0.9148 / R 0.6774
Tag: ORG - P 0.8121 / R 0.5411
Tag: PER - P 0.8766 / R 0.8057
Total time: 105.173842907
Epoch 2
Training loss: 0.972455978394978394
Training acc: 0.870769714322
Validation loss: 0.97530

/Users/prabhakar/tensorflow/lib/python2.7/site-packages/numpy/core/fromnumeric.py:2889: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)


In [18]:
test_NER()

Epoch 0
Training loss: 1.04275894165894165
Training acc: 0.809621797359
Validation loss: 0.997374296188

[[42472    30     0   116   141]
 [  269  1512     0   210   103]
 [  589   131     0   392   156]
 [  718    80     0  1149   145]
 [  568    23     0    56  2502]]
Tag: O - P 0.9519 / R 0.9933
Tag: LOC - P 0.8514 / R 0.7221
Tag: MISC - P nan / R 0.0000
Tag: ORG - P 0.5975 / R 0.5492
Tag: PER - P 0.8211 / R 0.7945
Total time: 101.427340984
Epoch 1
Training loss: 0.986922442913442913
Training acc: 0.860535013579
Validation loss: 0.980961978436

[[42396    27    40   119   177]
 [  193  1633    39   120   109]
 [  410    24   773    28    33]
 [  648   107    29  1190   118]
 [  442    22     3    32  2650]]
Tag: O - P 0.9616 / R 0.9915
Tag: LOC - P 0.9007 / R 0.7798
Tag: MISC - P 0.8744 / R 0.6096
Tag: ORG - P 0.7992 / R 0.5688
Tag: PER - P 0.8584 / R 0.8415
Total time: 99.8500649929
Epoch 2
Training loss: 0.972378671169671169
Training acc: 0.871624243079
Validation loss: 0.97551769

In [ ]:
test_NER()

Epoch 0
1710 / 3181 : loss = 1.08583903313